// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { InvokeCompareQuotesData, InvokeCompareQuotesErrors, InvokeCompareQuotesResponses, InvokeCreatePurchaseRequestData, InvokeCreatePurchaseRequestErrors, InvokeCreatePurchaseRequestResponses, InvokeDecidePurchaseRequestData, InvokeDecidePurchaseRequestErrors, InvokeDecidePurchaseRequestResponses, InvokeExecutiveDashboardData, InvokeExecutiveDashboardErrors, InvokeExecutiveDashboardResponses, InvokeIngestQuotePayloadsData, InvokeIngestQuotePayloadsErrors, InvokeIngestQuotePayloadsResponses, InvokeSupplierScorecardData, InvokeSupplierScorecardErrors, InvokeSupplierScorecardResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Ingest browser-uploaded quote payloads into structured procurement memory.
 *
 * Ingest browser-uploaded quote payloads into structured procurement memory.
 */
export const invokeIngestQuotePayloads = <ThrowOnError extends boolean = false>(options: Options<InvokeIngestQuotePayloadsData, ThrowOnError>): RequestResult<InvokeIngestQuotePayloadsResponses, InvokeIngestQuotePayloadsErrors, ThrowOnError> => (options.client ?? client).post<InvokeIngestQuotePayloadsResponses, InvokeIngestQuotePayloadsErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/invoke/ingest_quote_payloads',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Compare current and historical quotes for a part.
 *
 * Compare current and historical quotes for a part.
 */
export const invokeCompareQuotes = <ThrowOnError extends boolean = false>(options: Options<InvokeCompareQuotesData, ThrowOnError>): RequestResult<InvokeCompareQuotesResponses, InvokeCompareQuotesErrors, ThrowOnError> => (options.client ?? client).post<InvokeCompareQuotesResponses, InvokeCompareQuotesErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/invoke/compare_quotes',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Create a purchase request from a recommended or selected quote.
 *
 * Create a purchase request from a recommended or selected quote.
 */
export const invokeCreatePurchaseRequest = <ThrowOnError extends boolean = false>(options: Options<InvokeCreatePurchaseRequestData, ThrowOnError>): RequestResult<InvokeCreatePurchaseRequestResponses, InvokeCreatePurchaseRequestErrors, ThrowOnError> => (options.client ?? client).post<InvokeCreatePurchaseRequestResponses, InvokeCreatePurchaseRequestErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/invoke/create_purchase_request',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Approve, reject, or request more quotes for a purchase request.
 *
 * Approve, reject, or request more quotes for a purchase request.
 */
export const invokeDecidePurchaseRequest = <ThrowOnError extends boolean = false>(options: Options<InvokeDecidePurchaseRequestData, ThrowOnError>): RequestResult<InvokeDecidePurchaseRequestResponses, InvokeDecidePurchaseRequestErrors, ThrowOnError> => (options.client ?? client).post<InvokeDecidePurchaseRequestResponses, InvokeDecidePurchaseRequestErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/invoke/decide_purchase_request',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Return a supplier scorecard based on quotes and recorded outcomes.
 *
 * Return a supplier scorecard based on quotes and recorded outcomes.
 */
export const invokeSupplierScorecard = <ThrowOnError extends boolean = false>(options: Options<InvokeSupplierScorecardData, ThrowOnError>): RequestResult<InvokeSupplierScorecardResponses, InvokeSupplierScorecardErrors, ThrowOnError> => (options.client ?? client).post<InvokeSupplierScorecardResponses, InvokeSupplierScorecardErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/invoke/supplier_scorecard',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Return owner-level procurement KPIs for the current organization.
 *
 * Return owner-level procurement KPIs for the current organization.
 */
export const invokeExecutiveDashboard = <ThrowOnError extends boolean = false>(options: Options<InvokeExecutiveDashboardData, ThrowOnError>): RequestResult<InvokeExecutiveDashboardResponses, InvokeExecutiveDashboardErrors, ThrowOnError> => (options.client ?? client).post<InvokeExecutiveDashboardResponses, InvokeExecutiveDashboardErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/invoke/executive_dashboard',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
