// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type AgentEvent = {
    kind: string;
    payload: {
        [key: string]: unknown;
    };
};

export type AgentArtifact = {
    name: string;
    size_bytes: number;
};

export type InvokeError = {
    detail?: string | {
        [key: string]: unknown;
    };
    [key: string]: unknown;
};

export type LlmCreds = {
    base_url: string;
    api_key: string;
    model: string;
    temperature_mode?: string;
    temperature?: number | null;
    extra_body?: {
        [key: string]: unknown;
    } | null;
    metadata?: {
        [key: string]: unknown;
    } | null;
};

export type CompositionBudget = {
    [key: string]: unknown;
};

export type InvokeIngestQuotePayloadsData = {
    body: {
        arguments: {
            documents: Array<{
                /**
                 * Filename
                 */
                filename: string;
                /**
                 * Data Base64
                 *
                 * Base64-encoded PDF or text quote bytes.
                 */
                data_base64: string;
                /**
                 * Media Type
                 */
                media_type?: string;
            }>;
            requested_part?: string;
            requested_quantity?: number | null;
        };
        /**
         * Optional A2A workspace/sandbox grant token.
         */
        grant?: string | null;
        /**
         * Optional caller-provided LLM credentials.
         */
        llm_creds?: LlmCreds | null;
        composition?: CompositionBudget | null;
        consumer_config?: {
            [key: string]: unknown;
        } | null;
        consumer_secrets?: {
            [key: string]: string;
        } | null;
        /**
         * Optional control-plane JWT forwarded by trusted orchestrators.
         */
        cp_jwt?: string | null;
        /**
         * Optional control-plane base URL.
         */
        cp_url?: string | null;
    };
    path?: never;
    query?: never;
    url: '/invoke/ingest_quote_payloads';
};

export type InvokeIngestQuotePayloadsErrors = {
    /**
     * Invalid skill arguments.
     */
    400: InvokeError;
    /**
     * Missing or invalid authentication.
     */
    401: InvokeError;
    /**
     * Authentication succeeded but required scope or grant is missing.
     */
    403: InvokeError;
    /**
     * Unknown skill.
     */
    404: InvokeError;
    /**
     * Skill handler raised.
     */
    500: InvokeError;
};

export type InvokeIngestQuotePayloadsError = InvokeIngestQuotePayloadsErrors[keyof InvokeIngestQuotePayloadsErrors];

export type InvokeIngestQuotePayloadsResponses = {
    /**
     * Skill invocation completed.
     */
    200: {
        result: {
            [key: string]: unknown;
        };
        events: Array<AgentEvent>;
        artifacts: Array<AgentArtifact>;
        grant_id: string | null;
    };
};

export type InvokeIngestQuotePayloadsResponse = InvokeIngestQuotePayloadsResponses[keyof InvokeIngestQuotePayloadsResponses];

export type InvokeCompareQuotesData = {
    body: {
        arguments: {
            part_query: string;
            quantity?: number | null;
        };
        /**
         * Optional A2A workspace/sandbox grant token.
         */
        grant?: string | null;
        /**
         * Optional caller-provided LLM credentials.
         */
        llm_creds?: LlmCreds | null;
        composition?: CompositionBudget | null;
        consumer_config?: {
            [key: string]: unknown;
        } | null;
        consumer_secrets?: {
            [key: string]: string;
        } | null;
        /**
         * Optional control-plane JWT forwarded by trusted orchestrators.
         */
        cp_jwt?: string | null;
        /**
         * Optional control-plane base URL.
         */
        cp_url?: string | null;
    };
    path?: never;
    query?: never;
    url: '/invoke/compare_quotes';
};

export type InvokeCompareQuotesErrors = {
    /**
     * Invalid skill arguments.
     */
    400: InvokeError;
    /**
     * Missing or invalid authentication.
     */
    401: InvokeError;
    /**
     * Authentication succeeded but required scope or grant is missing.
     */
    403: InvokeError;
    /**
     * Unknown skill.
     */
    404: InvokeError;
    /**
     * Skill handler raised.
     */
    500: InvokeError;
};

export type InvokeCompareQuotesError = InvokeCompareQuotesErrors[keyof InvokeCompareQuotesErrors];

export type InvokeCompareQuotesResponses = {
    /**
     * Skill invocation completed.
     */
    200: {
        result: {
            [key: string]: unknown;
        };
        events: Array<AgentEvent>;
        artifacts: Array<AgentArtifact>;
        grant_id: string | null;
    };
};

export type InvokeCompareQuotesResponse = InvokeCompareQuotesResponses[keyof InvokeCompareQuotesResponses];

export type InvokeCreatePurchaseRequestData = {
    body: {
        arguments: {
            quote_line_item_id: number;
            quantity: number;
            reason?: string;
        };
        /**
         * Optional A2A workspace/sandbox grant token.
         */
        grant?: string | null;
        /**
         * Optional caller-provided LLM credentials.
         */
        llm_creds?: LlmCreds | null;
        composition?: CompositionBudget | null;
        consumer_config?: {
            [key: string]: unknown;
        } | null;
        consumer_secrets?: {
            [key: string]: string;
        } | null;
        /**
         * Optional control-plane JWT forwarded by trusted orchestrators.
         */
        cp_jwt?: string | null;
        /**
         * Optional control-plane base URL.
         */
        cp_url?: string | null;
    };
    path?: never;
    query?: never;
    url: '/invoke/create_purchase_request';
};

export type InvokeCreatePurchaseRequestErrors = {
    /**
     * Invalid skill arguments.
     */
    400: InvokeError;
    /**
     * Missing or invalid authentication.
     */
    401: InvokeError;
    /**
     * Authentication succeeded but required scope or grant is missing.
     */
    403: InvokeError;
    /**
     * Unknown skill.
     */
    404: InvokeError;
    /**
     * Skill handler raised.
     */
    500: InvokeError;
};

export type InvokeCreatePurchaseRequestError = InvokeCreatePurchaseRequestErrors[keyof InvokeCreatePurchaseRequestErrors];

export type InvokeCreatePurchaseRequestResponses = {
    /**
     * Skill invocation completed.
     */
    200: {
        result: {
            [key: string]: unknown;
        };
        events: Array<AgentEvent>;
        artifacts: Array<AgentArtifact>;
        grant_id: string | null;
    };
};

export type InvokeCreatePurchaseRequestResponse = InvokeCreatePurchaseRequestResponses[keyof InvokeCreatePurchaseRequestResponses];

export type InvokeDecidePurchaseRequestData = {
    body: {
        arguments: {
            request_id: number;
            decision: 'approve' | 'reject' | 'request_more_quotes';
            note?: string;
        };
        /**
         * Optional A2A workspace/sandbox grant token.
         */
        grant?: string | null;
        /**
         * Optional caller-provided LLM credentials.
         */
        llm_creds?: LlmCreds | null;
        composition?: CompositionBudget | null;
        consumer_config?: {
            [key: string]: unknown;
        } | null;
        consumer_secrets?: {
            [key: string]: string;
        } | null;
        /**
         * Optional control-plane JWT forwarded by trusted orchestrators.
         */
        cp_jwt?: string | null;
        /**
         * Optional control-plane base URL.
         */
        cp_url?: string | null;
    };
    path?: never;
    query?: never;
    url: '/invoke/decide_purchase_request';
};

export type InvokeDecidePurchaseRequestErrors = {
    /**
     * Invalid skill arguments.
     */
    400: InvokeError;
    /**
     * Missing or invalid authentication.
     */
    401: InvokeError;
    /**
     * Authentication succeeded but required scope or grant is missing.
     */
    403: InvokeError;
    /**
     * Unknown skill.
     */
    404: InvokeError;
    /**
     * Skill handler raised.
     */
    500: InvokeError;
};

export type InvokeDecidePurchaseRequestError = InvokeDecidePurchaseRequestErrors[keyof InvokeDecidePurchaseRequestErrors];

export type InvokeDecidePurchaseRequestResponses = {
    /**
     * Skill invocation completed.
     */
    200: {
        result: {
            [key: string]: unknown;
        };
        events: Array<AgentEvent>;
        artifacts: Array<AgentArtifact>;
        grant_id: string | null;
    };
};

export type InvokeDecidePurchaseRequestResponse = InvokeDecidePurchaseRequestResponses[keyof InvokeDecidePurchaseRequestResponses];

export type InvokeSupplierScorecardData = {
    body: {
        arguments: {
            supplier_name: string;
        };
        /**
         * Optional A2A workspace/sandbox grant token.
         */
        grant?: string | null;
        /**
         * Optional caller-provided LLM credentials.
         */
        llm_creds?: LlmCreds | null;
        composition?: CompositionBudget | null;
        consumer_config?: {
            [key: string]: unknown;
        } | null;
        consumer_secrets?: {
            [key: string]: string;
        } | null;
        /**
         * Optional control-plane JWT forwarded by trusted orchestrators.
         */
        cp_jwt?: string | null;
        /**
         * Optional control-plane base URL.
         */
        cp_url?: string | null;
    };
    path?: never;
    query?: never;
    url: '/invoke/supplier_scorecard';
};

export type InvokeSupplierScorecardErrors = {
    /**
     * Invalid skill arguments.
     */
    400: InvokeError;
    /**
     * Missing or invalid authentication.
     */
    401: InvokeError;
    /**
     * Authentication succeeded but required scope or grant is missing.
     */
    403: InvokeError;
    /**
     * Unknown skill.
     */
    404: InvokeError;
    /**
     * Skill handler raised.
     */
    500: InvokeError;
};

export type InvokeSupplierScorecardError = InvokeSupplierScorecardErrors[keyof InvokeSupplierScorecardErrors];

export type InvokeSupplierScorecardResponses = {
    /**
     * Skill invocation completed.
     */
    200: {
        result: {
            [key: string]: unknown;
        };
        events: Array<AgentEvent>;
        artifacts: Array<AgentArtifact>;
        grant_id: string | null;
    };
};

export type InvokeSupplierScorecardResponse = InvokeSupplierScorecardResponses[keyof InvokeSupplierScorecardResponses];

export type InvokeExecutiveDashboardData = {
    body: {
        arguments: {
            [key: string]: never;
        };
        /**
         * Optional A2A workspace/sandbox grant token.
         */
        grant?: string | null;
        /**
         * Optional caller-provided LLM credentials.
         */
        llm_creds?: LlmCreds | null;
        composition?: CompositionBudget | null;
        consumer_config?: {
            [key: string]: unknown;
        } | null;
        consumer_secrets?: {
            [key: string]: string;
        } | null;
        /**
         * Optional control-plane JWT forwarded by trusted orchestrators.
         */
        cp_jwt?: string | null;
        /**
         * Optional control-plane base URL.
         */
        cp_url?: string | null;
    };
    path?: never;
    query?: never;
    url: '/invoke/executive_dashboard';
};

export type InvokeExecutiveDashboardErrors = {
    /**
     * Invalid skill arguments.
     */
    400: InvokeError;
    /**
     * Missing or invalid authentication.
     */
    401: InvokeError;
    /**
     * Authentication succeeded but required scope or grant is missing.
     */
    403: InvokeError;
    /**
     * Unknown skill.
     */
    404: InvokeError;
    /**
     * Skill handler raised.
     */
    500: InvokeError;
};

export type InvokeExecutiveDashboardError = InvokeExecutiveDashboardErrors[keyof InvokeExecutiveDashboardErrors];

export type InvokeExecutiveDashboardResponses = {
    /**
     * Skill invocation completed.
     */
    200: {
        result: {
            [key: string]: unknown;
        };
        events: Array<AgentEvent>;
        artifacts: Array<AgentArtifact>;
        grant_id: string | null;
    };
};

export type InvokeExecutiveDashboardResponse = InvokeExecutiveDashboardResponses[keyof InvokeExecutiveDashboardResponses];
