"""Org-facing AI-compliance surface (EU AI Act, NIST AI RMF, ISO/IEC 42001).

Decision records are *not* a new store — they are a normalized, queryable
view over the three audit surfaces the platform already writes on every
run: signed execution receipts (``agent_receipts``), the grant decision
chain (``grant_audit``), and the org admin trail
(``organization_audit_logs``). This route layer adds:

* a per-org retention policy with the EU AI Act Art. 19 floor (180 days)
  enforced at write *and* purge time, plus legal hold;
* a unified ``/decision-records`` query API (Art. 12 requires logs to be
  automatically recorded — receipts already do that — and usable);
* per-agent risk classification (Act risk tiers) + procurement metadata;
* a self-contained evidence-pack export with the framework control
  mapping inlined, for procurement / auditor handoff.

Every export and purge is itself written to the org audit log, so access
to compliance data is part of the compliance data.
"""
from __future__ import annotations

from datetime import datetime, timedelta, timezone
from typing import Any, Literal

from fastapi import APIRouter, Depends, HTTPException, Query
from pydantic import BaseModel, Field
from sqlalchemy import delete, func as sa_func, select
from sqlalchemy.ext.asyncio import AsyncSession

from a2a_pack.receipts import ReceiptInvalid, verify_receipt

from ..agent_authorization import is_own_evidence, may_read_agent_evidence
from ..auth import current_user
from ..db import get_session
from ..models import (
    Agent,
    AgentComplianceProfile,
    AgentReceipt,
    GrantAudit,
    Organization,
    OrganizationAuditLog,
    OrganizationCompliancePolicy,
    OrganizationMember,
    User,
)
from .organizations import ADMIN_ROLES, _add_audit, _member_org

router = APIRouter(
    prefix="/v1/me/organizations/{slug}/compliance", tags=["compliance"]
)

# EU AI Act Art. 19: automatically generated logs are kept for at least
# six months. We floor at 180 days whenever the framework is active.
EU_AI_ACT_MIN_RETENTION_DAYS = 180
DEFAULT_RETENTION_DAYS = 180
MAX_RETENTION_DAYS = 3650
EU_AI_ACT_ENFORCEMENT_DATE = datetime(2026, 8, 2, tzinfo=timezone.utc)

KNOWN_FRAMEWORKS = ("eu_ai_act", "nist_ai_rmf_1_1", "iso_42001")
RISK_TIERS = ("unclassified", "minimal", "limited", "high", "unacceptable")
RECORD_KINDS = ("skill_execution", "authorization", "admin_action")

RecordKind = Literal["skill_execution", "authorization", "admin_action"]

# Static control mapping shipped inside every evidence pack so the export
# is self-describing for an auditor who has never seen this platform.
FRAMEWORK_CONTROLS: dict[str, list[dict[str, Any]]] = {
    "eu_ai_act": [
        {
            "control": "Article 12 — Record-keeping",
            "requirement": (
                "High-risk AI systems shall technically allow for the "
                "automatic recording of events (logs) over the lifetime "
                "of the system."
            ),
            "evidence": ["skill_execution", "authorization", "admin_action"],
            "implementation": (
                "Every skill invocation is sealed into an Ed25519-signed "
                "execution receipt (inputs hash, tool calls, file ops, "
                "handoffs, timing, status). Every authorization decision "
                "is a grant_audit row with a parent chain. Administrative "
                "actions land in the org audit log. All three are "
                "queryable via /decision-records."
            ),
        },
        {
            "control": "Article 19 — Automatically generated logs",
            "requirement": (
                "Providers keep the logs automatically generated by their "
                "high-risk AI systems for at least six months."
            ),
            "evidence": ["retention_policy"],
            "implementation": (
                "Org retention policy is floored at 180 days while "
                "eu_ai_act is active; the floor is re-checked inside the "
                "purge path and legal hold blocks deletion entirely."
            ),
        },
        {
            "control": "Article 14 — Human oversight",
            "requirement": (
                "High-risk AI systems are designed so natural persons can "
                "effectively oversee them."
            ),
            "evidence": ["authorization", "agent_inventory"],
            "implementation": (
                "Grant decisions record decided_by (auto|user|policy), so "
                "human-in-the-loop approvals are distinguishable from "
                "automatic ones. Each agent's compliance profile carries a "
                "human_oversight statement."
            ),
        },
        {
            "control": "Article 11 — Technical documentation",
            "requirement": (
                "Technical documentation is drawn up before placing on "
                "the market and kept up to date."
            ),
            "evidence": ["agent_inventory"],
            "implementation": (
                "Agent card (capabilities, version, image) plus the "
                "compliance profile (risk tier, intended purpose) form the "
                "per-system documentation exported in the evidence pack."
            ),
        },
    ],
    "nist_ai_rmf_1_1": [
        {
            "control": "GOVERN",
            "requirement": "Policies, processes and accountability for AI risk.",
            "evidence": ["retention_policy", "admin_action"],
            "implementation": (
                "Org-level compliance policy with named updater, admin "
                "audit trail for every governance action."
            ),
        },
        {
            "control": "MAP",
            "requirement": "Context and risks of AI systems are identified.",
            "evidence": ["agent_inventory"],
            "implementation": (
                "Agent inventory with per-agent risk tier and intended "
                "purpose."
            ),
        },
        {
            "control": "MEASURE",
            "requirement": "AI risks are analyzed, assessed and tracked.",
            "evidence": ["skill_execution"],
            "implementation": (
                "Receipts carry eval_score and reviewer fields; execution "
                "outcomes are queryable by status over time."
            ),
        },
        {
            "control": "MANAGE",
            "requirement": "Risks are prioritized and acted upon.",
            "evidence": ["authorization", "retention_policy"],
            "implementation": (
                "Scoped grants bound what agents may touch; composition "
                "budgets cap spend; legal hold and floored purge control "
                "the record lifecycle."
            ),
        },
    ],
    "iso_42001": [
        {
            "control": "ISO/IEC 42001 §6 — Planning",
            "requirement": "AI risk assessment and treatment.",
            "evidence": ["agent_inventory"],
            "implementation": "Per-agent risk classification with review metadata.",
        },
        {
            "control": "ISO/IEC 42001 §8 — Operation",
            "requirement": "Operational control of AI systems.",
            "evidence": ["skill_execution", "authorization"],
            "implementation": (
                "Signed receipts prove what ran under which authority; "
                "grant chain reconstructs the scope negotiation."
            ),
        },
        {
            "control": "ISO/IEC 42001 §9 — Performance evaluation",
            "requirement": "Monitoring, measurement, analysis and evaluation.",
            "evidence": ["skill_execution", "admin_action"],
            "implementation": (
                "Eval scores on receipts; audit log covers internal "
                "reviews including evidence-pack exports."
            ),
        },
    ],
}


# ---------------------------------------------------------------------------
# Schemas


class CompliancePolicyOut(BaseModel):
    frameworks: list[str]
    retention_days: int
    retention_floor_days: int
    legal_hold: bool
    legal_hold_reason: str | None
    updated_at: datetime | None
    persisted: bool


class CompliancePolicyIn(BaseModel):
    frameworks: list[str] = Field(default_factory=lambda: ["eu_ai_act"])
    retention_days: int = Field(default=DEFAULT_RETENTION_DAYS, ge=1, le=MAX_RETENTION_DAYS)
    legal_hold: bool = False
    legal_hold_reason: str | None = Field(default=None, max_length=2000)


class DecisionRecordOut(BaseModel):
    record_id: str
    kind: RecordKind
    recorded_at: datetime
    occurred_at: datetime
    agent_name: str | None
    actor: str
    action: str
    outcome: str
    verifiable: bool
    details: dict[str, Any]


class DecisionRecordDetailOut(DecisionRecordOut):
    signed_token: str | None = None
    signature_status: Literal["valid", "invalid", "not_applicable"] = "not_applicable"
    payload: dict[str, Any] = Field(default_factory=dict)


class AgentRiskProfileOut(BaseModel):
    agent_name: str
    agent_version: str
    risk_tier: str
    intended_purpose: str
    human_oversight: str
    notes: str
    updated_at: datetime | None


class AgentRiskProfileIn(BaseModel):
    risk_tier: str = "unclassified"
    intended_purpose: str = ""
    human_oversight: str = ""
    notes: str = ""


class ComplianceStatusOut(BaseModel):
    policy: CompliancePolicyOut
    retention_ok: bool
    enforcement_date: datetime
    days_until_enforcement: int
    record_counts: dict[str, int]
    oldest_record_at: datetime | None
    agents_total: int
    agents_classified: int
    agents_high_risk: int


class EvidenceExportIn(BaseModel):
    from_at: datetime | None = None
    to_at: datetime | None = None
    kinds: list[RecordKind] = Field(default_factory=lambda: list(RECORD_KINDS))
    max_records: int = Field(default=1000, ge=1, le=5000)
    verify_signatures: bool = True


class RetentionEnforceOut(BaseModel):
    cutoff: datetime
    receipts_deleted: int
    admin_actions_deleted: int
    note: str


# ---------------------------------------------------------------------------
# Helpers


def _retention_floor(frameworks: list[str]) -> int:
    return EU_AI_ACT_MIN_RETENTION_DAYS if "eu_ai_act" in frameworks else 1


async def _policy_row(
    org: Organization, session: AsyncSession
) -> OrganizationCompliancePolicy | None:
    return (
        await session.execute(
            select(OrganizationCompliancePolicy).where(
                OrganizationCompliancePolicy.organization_id == org.id
            )
        )
    ).scalar_one_or_none()


def _policy_out(row: OrganizationCompliancePolicy | None) -> CompliancePolicyOut:
    frameworks = list(row.frameworks) if row is not None else ["eu_ai_act"]
    return CompliancePolicyOut(
        frameworks=frameworks,
        retention_days=row.retention_days if row is not None else DEFAULT_RETENTION_DAYS,
        retention_floor_days=_retention_floor(frameworks),
        legal_hold=row.legal_hold if row is not None else False,
        legal_hold_reason=row.legal_hold_reason if row is not None else None,
        updated_at=row.updated_at if row is not None else None,
        persisted=row is not None,
    )


def _receipt_record(row: AgentReceipt) -> DecisionRecordOut:
    payload = row.payload or {}
    return DecisionRecordOut(
        record_id=row.receipt_id,
        kind="skill_execution",
        recorded_at=row.created_at,
        occurred_at=row.started_at or row.created_at,
        agent_name=row.agent_name,
        actor=row.caller or "unknown",
        action=f"skill:{row.skill_name}",
        outcome=row.status,
        verifiable=True,
        details={
            "task_id": row.task_id,
            "agent_version": row.agent_version,
            "elapsed_ms": row.elapsed_ms,
            "eval_score": row.eval_score,
            "grant_ids": payload.get("grant_ids", []),
            "tool_calls": len(payload.get("tool_calls", []) or []),
            "handoffs": len(payload.get("handoffs", []) or []),
        },
    )


def _grant_record(row: GrantAudit) -> DecisionRecordOut:
    return DecisionRecordOut(
        record_id=row.grant_id,
        kind="authorization",
        recorded_at=row.created_at,
        occurred_at=row.created_at,
        agent_name=row.audience,
        actor=row.issuer,
        action=f"grant:{row.bucket}:{row.mode}",
        outcome=row.decision,
        verifiable=False,
        details={
            "decided_by": row.decided_by,
            "reason": row.reason,
            "parent_grant_id": row.parent_grant_id,
            "ttl_seconds": row.ttl_seconds,
            "allow_patterns": row.allow_patterns or [],
            "deny_patterns": row.deny_patterns or [],
        },
    )


def _admin_record(row: OrganizationAuditLog) -> DecisionRecordOut:
    return DecisionRecordOut(
        record_id=f"orgaudit-{row.id}",
        kind="admin_action",
        recorded_at=row.created_at,
        occurred_at=row.created_at,
        agent_name=None,
        actor=row.actor or "system",
        action=row.action,
        outcome="recorded",
        verifiable=False,
        details={
            "target_type": row.target_type,
            "target_id": row.target_id,
            "target_email": row.target_email,
            "data": row.data or {},
        },
    )


def _time_bounds(stmt, column, from_at: datetime | None, to_at: datetime | None):
    if from_at is not None:
        stmt = stmt.where(column >= from_at)
    if to_at is not None:
        stmt = stmt.where(column < to_at)
    return stmt


async def _query_receipts(
    org: Organization,
    session: AsyncSession,
    *,
    agent: str | None,
    outcome: str | None,
    from_at: datetime | None,
    to_at: datetime | None,
    limit: int,
) -> list[AgentReceipt]:
    stmt = (
        select(AgentReceipt)
        .join(Agent, Agent.id == AgentReceipt.agent_id)
        .where(Agent.organization_id == org.id)
        .order_by(AgentReceipt.created_at.desc())
        .limit(limit)
    )
    if agent:
        stmt = stmt.where(AgentReceipt.agent_name == agent)
    if outcome:
        stmt = stmt.where(AgentReceipt.status == outcome)
    stmt = _time_bounds(stmt, AgentReceipt.created_at, from_at, to_at)
    return list((await session.execute(stmt)).scalars().all())


async def _query_grants(
    org: Organization,
    session: AsyncSession,
    *,
    agent: str | None,
    outcome: str | None,
    from_at: datetime | None,
    to_at: datetime | None,
    limit: int,
) -> list[GrantAudit]:
    member_ids = select(OrganizationMember.user_id).where(
        OrganizationMember.organization_id == org.id
    )
    stmt = (
        select(GrantAudit)
        .where(GrantAudit.user_id.in_(member_ids))
        .order_by(GrantAudit.created_at.desc())
        .limit(limit)
    )
    if agent:
        stmt = stmt.where(GrantAudit.audience == agent)
    if outcome:
        stmt = stmt.where(GrantAudit.decision == outcome)
    stmt = _time_bounds(stmt, GrantAudit.created_at, from_at, to_at)
    return list((await session.execute(stmt)).scalars().all())


async def _query_admin_actions(
    org: Organization,
    session: AsyncSession,
    *,
    from_at: datetime | None,
    to_at: datetime | None,
    limit: int,
) -> list[OrganizationAuditLog]:
    stmt = (
        select(OrganizationAuditLog)
        .where(OrganizationAuditLog.organization_id == org.id)
        .order_by(OrganizationAuditLog.created_at.desc())
        .limit(limit)
    )
    stmt = _time_bounds(stmt, OrganizationAuditLog.created_at, from_at, to_at)
    return list((await session.execute(stmt)).scalars().all())


async def _collect_records(
    org: Organization,
    session: AsyncSession,
    *,
    kinds: list[str],
    agent: str | None = None,
    outcome: str | None = None,
    from_at: datetime | None = None,
    to_at: datetime | None = None,
    limit: int = 100,
) -> list[DecisionRecordOut]:
    records: list[DecisionRecordOut] = []
    if "skill_execution" in kinds:
        records += [
            _receipt_record(r)
            for r in await _query_receipts(
                org, session, agent=agent, outcome=outcome,
                from_at=from_at, to_at=to_at, limit=limit,
            )
        ]
    if "authorization" in kinds:
        records += [
            _grant_record(r)
            for r in await _query_grants(
                org, session, agent=agent, outcome=outcome,
                from_at=from_at, to_at=to_at, limit=limit,
            )
        ]
    if "admin_action" in kinds and not agent and not outcome:
        records += [
            _admin_record(r)
            for r in await _query_admin_actions(
                org, session, from_at=from_at, to_at=to_at, limit=limit,
            )
        ]
    records.sort(key=lambda r: r.recorded_at, reverse=True)
    return records[:limit]


# ---------------------------------------------------------------------------
# Policy


@router.get("/policy", response_model=CompliancePolicyOut)
async def get_policy(
    slug: str,
    user: User = Depends(current_user),
    session: AsyncSession = Depends(get_session),
) -> CompliancePolicyOut:
    org, _ = await _member_org(slug, user, session, admin=True)
    return _policy_out(await _policy_row(org, session))


@router.put("/policy", response_model=CompliancePolicyOut)
async def put_policy(
    slug: str,
    body: CompliancePolicyIn,
    user: User = Depends(current_user),
    session: AsyncSession = Depends(get_session),
) -> CompliancePolicyOut:
    org, _ = await _member_org(slug, user, session, admin=True)
    unknown = [f for f in body.frameworks if f not in KNOWN_FRAMEWORKS]
    if unknown:
        raise HTTPException(422, f"unknown frameworks: {unknown}")
    floor = _retention_floor(body.frameworks)
    if body.retention_days < floor:
        raise HTTPException(
            422,
            f"retention_days {body.retention_days} below the {floor}-day floor "
            "required while eu_ai_act is active (EU AI Act Art. 19)",
        )
    row = await _policy_row(org, session)
    if row is None:
        row = OrganizationCompliancePolicy(organization_id=org.id)
        session.add(row)
    row.frameworks = list(dict.fromkeys(body.frameworks))
    row.retention_days = body.retention_days
    row.legal_hold = body.legal_hold
    row.legal_hold_reason = body.legal_hold_reason if body.legal_hold else None
    row.updated_by_id = user.id
    _add_audit(
        session,
        org_id=org.id,
        action="compliance.policy_updated",
        target_type="compliance_policy",
        actor_user=user,
        data={
            "frameworks": row.frameworks,
            "retention_days": row.retention_days,
            "legal_hold": row.legal_hold,
        },
    )
    await session.commit()
    await session.refresh(row)
    return _policy_out(row)


# ---------------------------------------------------------------------------
# Status


@router.get("/status", response_model=ComplianceStatusOut)
async def get_status(
    slug: str,
    user: User = Depends(current_user),
    session: AsyncSession = Depends(get_session),
) -> ComplianceStatusOut:
    org, _ = await _member_org(slug, user, session, admin=True)
    policy = _policy_out(await _policy_row(org, session))

    receipt_count, oldest_receipt = (
        await session.execute(
            select(sa_func.count(), sa_func.min(AgentReceipt.created_at))
            .select_from(AgentReceipt)
            .join(Agent, Agent.id == AgentReceipt.agent_id)
            .where(Agent.organization_id == org.id)
        )
    ).one()
    member_ids = select(OrganizationMember.user_id).where(
        OrganizationMember.organization_id == org.id
    )
    grant_count = (
        await session.execute(
            select(sa_func.count()).select_from(GrantAudit).where(
                GrantAudit.user_id.in_(member_ids)
            )
        )
    ).scalar_one()
    admin_count = (
        await session.execute(
            select(sa_func.count()).select_from(OrganizationAuditLog).where(
                OrganizationAuditLog.organization_id == org.id
            )
        )
    ).scalar_one()

    agents_total = (
        await session.execute(
            select(sa_func.count()).select_from(Agent).where(
                Agent.organization_id == org.id
            )
        )
    ).scalar_one()
    agents_classified = (
        await session.execute(
            select(sa_func.count())
            .select_from(AgentComplianceProfile)
            .where(
                AgentComplianceProfile.organization_id == org.id,
                AgentComplianceProfile.risk_tier != "unclassified",
            )
        )
    ).scalar_one()
    agents_high_risk = (
        await session.execute(
            select(sa_func.count())
            .select_from(AgentComplianceProfile)
            .where(
                AgentComplianceProfile.organization_id == org.id,
                AgentComplianceProfile.risk_tier.in_(("high", "unacceptable")),
            )
        )
    ).scalar_one()

    now = datetime.now(timezone.utc)
    return ComplianceStatusOut(
        policy=policy,
        retention_ok=policy.retention_days >= policy.retention_floor_days,
        enforcement_date=EU_AI_ACT_ENFORCEMENT_DATE,
        days_until_enforcement=max(0, (EU_AI_ACT_ENFORCEMENT_DATE - now).days),
        record_counts={
            "skill_execution": int(receipt_count),
            "authorization": int(grant_count),
            "admin_action": int(admin_count),
        },
        oldest_record_at=oldest_receipt,
        agents_total=int(agents_total),
        agents_classified=int(agents_classified),
        agents_high_risk=int(agents_high_risk),
    )


# ---------------------------------------------------------------------------
# Decision records


@router.get("/decision-records", response_model=list[DecisionRecordOut])
async def list_decision_records(
    slug: str,
    kind: str | None = Query(default=None),
    agent: str | None = Query(default=None),
    outcome: str | None = Query(default=None),
    from_at: datetime | None = Query(default=None),
    to_at: datetime | None = Query(default=None),
    limit: int = Query(default=100, ge=1, le=500),
    user: User = Depends(current_user),
    session: AsyncSession = Depends(get_session),
) -> list[DecisionRecordOut]:
    org, _ = await _member_org(slug, user, session, admin=True)
    if kind is not None and kind not in RECORD_KINDS:
        raise HTTPException(422, f"kind must be one of {RECORD_KINDS}")
    kinds = [kind] if kind else list(RECORD_KINDS)
    return await _collect_records(
        org, session, kinds=kinds, agent=agent, outcome=outcome,
        from_at=from_at, to_at=to_at, limit=limit,
    )


@router.get(
    "/decision-records/{kind}/{record_id}",
    response_model=DecisionRecordDetailOut,
)
async def get_decision_record(
    slug: str,
    kind: RecordKind,
    record_id: str,
    user: User = Depends(current_user),
    session: AsyncSession = Depends(get_session),
) -> DecisionRecordDetailOut:
    # ``skill_execution`` is the one kind whose detail body is byte-identical to
    # what ``GET /v1/agents/{name}/receipts/{id}`` serves — the signed token plus
    # the full receipt payload, which carries the *caller's* prompt text. It is
    # therefore gated by exactly the rule that route applies — an evidence
    # reader (``agent_authorization.may_read_agent_evidence``) or the receipt's
    # own caller (``is_own_evidence``) — rather than by a second,
    # independently-written org-role check: when these two disagreed, the
    # narrower one was decorative. The other kinds are org-wide audit surfaces
    # with no per-agent owner to consult, so they stay org owner/admin.
    org, member = await _member_org(slug, user, session)

    if kind == "skill_execution":
        found = (
            await session.execute(
                select(AgentReceipt, Agent)
                .join(Agent, Agent.id == AgentReceipt.agent_id)
                .where(
                    Agent.organization_id == org.id,
                    AgentReceipt.receipt_id == record_id,
                )
            )
        ).first()
        if found is None:
            raise HTTPException(404, "decision record not found")
        row, agent = found
        if not (
            await may_read_agent_evidence(session, user=user, agent=agent)
            or is_own_evidence(row.caller, user)
        ):
            raise HTTPException(
                403, "not authorized to view this agent's receipts"
            )
        try:
            verify_receipt(row.signed_token)
            signature_status = "valid"
        except ReceiptInvalid:
            signature_status = "invalid"
        return DecisionRecordDetailOut(
            **_receipt_record(row).model_dump(),
            signed_token=row.signed_token,
            signature_status=signature_status,
            payload=row.payload or {},
        )

    if member.role not in ADMIN_ROLES:
        raise HTTPException(403, "organization admin required")

    if kind == "authorization":
        member_ids = select(OrganizationMember.user_id).where(
            OrganizationMember.organization_id == org.id
        )
        row = (
            await session.execute(
                select(GrantAudit).where(
                    GrantAudit.grant_id == record_id,
                    GrantAudit.user_id.in_(member_ids),
                )
            )
        ).scalar_one_or_none()
        if row is None:
            raise HTTPException(404, "decision record not found")
        return DecisionRecordDetailOut(**_grant_record(row).model_dump())

    audit_id = record_id.removeprefix("orgaudit-")
    if not audit_id.isdigit():
        raise HTTPException(404, "decision record not found")
    row = (
        await session.execute(
            select(OrganizationAuditLog).where(
                OrganizationAuditLog.id == int(audit_id),
                OrganizationAuditLog.organization_id == org.id,
            )
        )
    ).scalar_one_or_none()
    if row is None:
        raise HTTPException(404, "decision record not found")
    return DecisionRecordDetailOut(**_admin_record(row).model_dump())


# ---------------------------------------------------------------------------
# Agent risk profiles


@router.get("/agents", response_model=list[AgentRiskProfileOut])
async def list_agent_profiles(
    slug: str,
    user: User = Depends(current_user),
    session: AsyncSession = Depends(get_session),
) -> list[AgentRiskProfileOut]:
    org, _ = await _member_org(slug, user, session, admin=True)
    rows = (
        await session.execute(
            select(Agent, AgentComplianceProfile)
            .outerjoin(
                AgentComplianceProfile,
                AgentComplianceProfile.agent_id == Agent.id,
            )
            .where(Agent.organization_id == org.id)
            .order_by(Agent.name)
        )
    ).all()
    return [
        AgentRiskProfileOut(
            agent_name=agent.name,
            agent_version=agent.version,
            risk_tier=profile.risk_tier if profile else "unclassified",
            intended_purpose=profile.intended_purpose if profile else "",
            human_oversight=profile.human_oversight if profile else "",
            notes=profile.notes if profile else "",
            updated_at=profile.updated_at if profile else None,
        )
        for agent, profile in rows
    ]


@router.put("/agents/{agent_name}", response_model=AgentRiskProfileOut)
async def put_agent_profile(
    slug: str,
    agent_name: str,
    body: AgentRiskProfileIn,
    user: User = Depends(current_user),
    session: AsyncSession = Depends(get_session),
) -> AgentRiskProfileOut:
    org, _ = await _member_org(slug, user, session, admin=True)
    if body.risk_tier not in RISK_TIERS:
        raise HTTPException(422, f"risk_tier must be one of {RISK_TIERS}")
    agent = (
        await session.execute(
            select(Agent).where(
                Agent.name == agent_name, Agent.organization_id == org.id
            )
        )
    ).scalar_one_or_none()
    if agent is None:
        raise HTTPException(404, "agent not found in this organization")
    profile = (
        await session.execute(
            select(AgentComplianceProfile).where(
                AgentComplianceProfile.agent_id == agent.id
            )
        )
    ).scalar_one_or_none()
    if profile is None:
        profile = AgentComplianceProfile(agent_id=agent.id, organization_id=org.id)
        session.add(profile)
    profile.organization_id = org.id
    profile.risk_tier = body.risk_tier
    profile.intended_purpose = body.intended_purpose
    profile.human_oversight = body.human_oversight
    profile.notes = body.notes
    profile.updated_by_id = user.id
    _add_audit(
        session,
        org_id=org.id,
        action="compliance.agent_classified",
        target_type="agent",
        actor_user=user,
        target_id=agent.name,
        data={"risk_tier": body.risk_tier},
    )
    await session.commit()
    await session.refresh(profile)
    return AgentRiskProfileOut(
        agent_name=agent.name,
        agent_version=agent.version,
        risk_tier=profile.risk_tier,
        intended_purpose=profile.intended_purpose,
        human_oversight=profile.human_oversight,
        notes=profile.notes,
        updated_at=profile.updated_at,
    )


# ---------------------------------------------------------------------------
# Evidence export


@router.post("/export")
async def export_evidence_pack(
    slug: str,
    body: EvidenceExportIn,
    user: User = Depends(current_user),
    session: AsyncSession = Depends(get_session),
) -> dict[str, Any]:
    org, _ = await _member_org(slug, user, session, admin=True)
    policy = _policy_out(await _policy_row(org, session))

    records = await _collect_records(
        org, session, kinds=list(body.kinds),
        from_at=body.from_at, to_at=body.to_at, limit=body.max_records,
    )

    verification = {"checked": 0, "valid": 0, "invalid": []}
    if body.verify_signatures and "skill_execution" in body.kinds:
        receipt_ids = [r.record_id for r in records if r.kind == "skill_execution"]
        if receipt_ids:
            rows = (
                await session.execute(
                    select(AgentReceipt.receipt_id, AgentReceipt.signed_token).where(
                        AgentReceipt.receipt_id.in_(receipt_ids)
                    )
                )
            ).all()
            for receipt_id, signed_token in rows:
                verification["checked"] += 1
                try:
                    verify_receipt(signed_token)
                    verification["valid"] += 1
                except ReceiptInvalid:
                    verification["invalid"].append(receipt_id)

    profile_rows = (
        await session.execute(
            select(Agent, AgentComplianceProfile)
            .outerjoin(
                AgentComplianceProfile,
                AgentComplianceProfile.agent_id == Agent.id,
            )
            .where(Agent.organization_id == org.id)
            .order_by(Agent.name)
        )
    ).all()
    inventory = [
        {
            "agent_name": agent.name,
            "agent_version": agent.version,
            "image": agent.image,
            "status": agent.status,
            "risk_tier": profile.risk_tier if profile else "unclassified",
            "intended_purpose": profile.intended_purpose if profile else "",
            "human_oversight": profile.human_oversight if profile else "",
        }
        for agent, profile in profile_rows
    ]

    _add_audit(
        session,
        org_id=org.id,
        action="compliance.evidence_exported",
        target_type="compliance_export",
        actor_user=user,
        data={
            "kinds": list(body.kinds),
            "record_count": len(records),
            "from_at": body.from_at.isoformat() if body.from_at else None,
            "to_at": body.to_at.isoformat() if body.to_at else None,
        },
    )
    await session.commit()

    now = datetime.now(timezone.utc)
    counts: dict[str, int] = {}
    for record in records:
        counts[record.kind] = counts.get(record.kind, 0) + 1
    return {
        "evidence_pack_version": "1",
        "generated_at": now.isoformat(),
        "generated_by": user.email,
        "organization": {"slug": org.slug, "name": org.name},
        "policy": policy.model_dump(mode="json"),
        "framework_controls": {
            f: FRAMEWORK_CONTROLS[f]
            for f in policy.frameworks
            if f in FRAMEWORK_CONTROLS
        },
        "agent_inventory": inventory,
        "record_counts": counts,
        "records": [r.model_dump(mode="json") for r in records],
        "signature_verification": verification,
        "truncated": len(records) >= body.max_records,
    }


# ---------------------------------------------------------------------------
# Retention enforcement


@router.post("/retention/enforce", response_model=RetentionEnforceOut)
async def enforce_retention(
    slug: str,
    user: User = Depends(current_user),
    session: AsyncSession = Depends(get_session),
) -> RetentionEnforceOut:
    org, member = await _member_org(slug, user, session, admin=True)
    if member.role != "owner":
        raise HTTPException(403, "organization owner required to purge records")
    row = await _policy_row(org, session)
    policy = _policy_out(row)
    if policy.legal_hold:
        raise HTTPException(
            409, "legal hold is active; retention purge is blocked"
        )
    # Re-derive the floor here: even if a stale/hand-edited policy row says
    # fewer days, the purge never reaches inside the Art. 19 window.
    effective_days = max(policy.retention_days, policy.retention_floor_days)
    cutoff = datetime.now(timezone.utc) - timedelta(days=effective_days)

    org_agent_ids = select(Agent.id).where(Agent.organization_id == org.id)
    receipts_deleted = (
        await session.execute(
            delete(AgentReceipt).where(
                AgentReceipt.agent_id.in_(org_agent_ids),
                AgentReceipt.created_at < cutoff,
            )
        )
    ).rowcount or 0
    admin_deleted = (
        await session.execute(
            delete(OrganizationAuditLog).where(
                OrganizationAuditLog.organization_id == org.id,
                OrganizationAuditLog.created_at < cutoff,
            )
        )
    ).rowcount or 0

    _add_audit(
        session,
        org_id=org.id,
        action="compliance.retention_enforced",
        target_type="compliance_policy",
        actor_user=user,
        data={
            "cutoff": cutoff.isoformat(),
            "receipts_deleted": receipts_deleted,
            "admin_actions_deleted": admin_deleted,
        },
    )
    await session.commit()
    return RetentionEnforceOut(
        cutoff=cutoff,
        receipts_deleted=receipts_deleted,
        admin_actions_deleted=admin_deleted,
        note=(
            "grant_audit rows are platform-scoped (a user may belong to "
            "several orgs) and are never purged by org-level retention"
        ),
    )
